[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
glam = "0.22.0"
nom = "7.1.1"
pathfinding = "4.1.1"
sscanf = "0.4.0"
